### ISSUE TITLE
Mix with dropmining

### ISSUE THREAD

**Issue by cyberblast** [ScreepsGamers/screeps.behaviour-action-pattern#124]
Currently it's an all or nothing decision. Do dropmining or not. But there are situations when it's good and some when it's not. So this requires an enhancement. 

Dropmining may be used (auto, per miner), when: 
* mining container is full
* no mining container present (IN, at the source)

but only when
* at least 1 hauler present (else carry yourself)

problem to solve
* picking is only possible, when there is no enemy, because they drop too (at least first corpses) and that would lure haulers to go there and they may die

possible solution: 
* when invaders present, only pickup energy in near of source => in picking.newTarget

There is no need for an additional action (dropping). Dropping may be included in harvesting (conditional).

**Comment by torin555** [comment]
+1 for this
