### ISSUE TITLE
static spot assignments for upgraders and miners

### ISSUE THREAD

**Issue by mikiones** [ScreepsGamers/screeps.behaviour-action-pattern#127]
the miners and upgraders should not call distance to position each tick. indeed assign position up front. and once reached just preform action.

**Comment by mikiones** [comment]
for example the upgraders container have in best option 8 spots open we can start assigning spots to upgrader(s) by next to closest to controller so is not in way of haulers

**Comment by cyberblast** [comment]
Currently there is only up to 1 upgrader. so it can take seat on the container. 
I don't think range calculation is a big issue, its only a simple arithmetic operation using the x and y coordinates of the pos, not like path distance (which is surely expensive). 
But yes of course, there may still be a faster way. 
On the other hand I think we are currently quite ok with cpu workload, so maybe we should focus on other things first. 
I really want to complete this container chapter quite soon, as I think it's still not the best way. "Links" is the next topic ;) 
But there are still some open points with containers (e.g. #109 ) which are first in the queue... 
I would really love to do more and faster, but can't find as much time for it as I'd like to. 
But we are progressing continuously and I think we are on a good way :)

**Comment by cyberblast** [comment]
> the miners and upgraders should not call distance to position each tick 
I took some care about that. the only range calculation left now is to the assigned location. 
That means "work" will only start when location reached (instead range calculation to container, to link, to source, to controller)
