### ISSUE TITLE
Assign Claimers to a specific reserve flagged room

### ISSUE THREAD

**Issue by torin555** [ScreepsGamers/screeps.behaviour-action-pattern#152]
At the moment Claimers are not assigned to a specific reserve flagged room, meaning you can only have one reserve flag (or the claimers will just try to bounce back and forth between the two rooms accomplishing nothing.) Claimers should be assigned to a specific flag/room when they are spawned to allow for multiple room reservations.

**Comment by cyberblast** [comment]
But it was working already... something broken

**Comment by cyberblast** [comment]
I can't find a reason why they should leave the current controller :/

**Comment by cyberblast** [comment]
I mean - yes we can implement a fixed assignment, but I'd really like to know whats going on there - why they are leaving. Maybe there is an other bug hidden, causing this behaviour...

**Comment by mikiones** [comment]
what if you have it 'claimed' on 5k already then wait ? better cycle around and fill to max and go to closest short cool down

**Comment by cyberblast** [comment]
This is a valid point.

**Comment by cyberblast** [comment]
Does anybody still experience the issue? 
I don't see any 'older' claimer moving around. 
May also be due to adjusted spawning and targetting rules for claimers. 

Is there anything to do here or is the current state sufficient?
