### ISSUE TITLE
TypeError: this.memory.sources.forEach is not a function

### ISSUE THREAD

**Issue by torin555** [ScreepsGamers/screeps.behaviour-action-pattern#154]
Getting this error when cloning a fresh copy directly from dev:
```
room:16
                        this.memory.sources.forEach(addSource);
                                            ^
TypeError: this.memory.sources.forEach is not a function
    at Room.Object.defineProperties.sources.get (room:16:45)
    at Room.Object.defineProperties.sourceEnergyAvailable.get (room:40:39)
    at action.isValidAction (creep.action.harvesting:22:15)
    at validateActionTarget (creep.Action:141:18)
    at entry (population:211:43)
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)
    at Function.<anonymous> (/opt/engine/node_modules/lodash/index.js:3346:13)
```

**Comment by cyberblast** [comment]
you can also try to delete the sources object at the root of the memory. 
I guess you are in simulation: custom mode? :D

**Comment by torin555** [comment]
No not in simulation. Tried completely removing the memory for each room. No dice.

**Comment by cyberblast** [comment]
:( strange. are there sources in the room we are talking about?

**Comment by torin555** [comment]
I don't even know which room is calling the error, but there are sources in every room in the game to my knowledge...

**Comment by cyberblast** [comment]
try to change room.js: 16
from: this.memory.sources.forEach(addSource);
to: if( this.memory.sources ) this.memory.sources.forEach(addSource);

**Comment by torin555** [comment]
the error isn't saying the result of the function is undefined, it's saying the function itself doesn't exist.

**Comment by cyberblast** [comment]
beacause sources is null and null doesnt have a function called forEach

**Comment by torin555** [comment]
mmm... Maybe, except sources isn't null...

**Comment by cyberblast** [comment]
exactly

**Comment by cyberblast** [comment]
or you could do 
if( this.memory.sources && Array.isArray(this.memory.sources) )

**Comment by cyberblast** [comment]
But this is only a walkaround to a problem we don't know. Why is it there? 


                    if( _.isUndefined(this.memory.sources) ) {                        
                        this._sources = this.find(FIND_SOURCES);

shouzld always give an array

**Comment by mikiones** [comment]
in console do:
Object.keys(Memory.rooms).forEach(e => Memory.rooms[e] = undefined)
shudle wipe all rooms cache out

**Comment by cyberblast** [comment]
I also had some strange bugs for a while. I had to continuously delete a memory value (each loop), because it came back each loop :/ 

I think "they" are also working hard at the code sometimes, and development includes errors...

**Comment by mikiones** [comment]
you need stop yr code while editing memory ;)
change branch to empty one edit mem and change back to dev...

**Comment by cyberblast** [comment]
then its a bug with the delete button in the mem editor

**Comment by torin555** [comment]
@mikiones That's basically what I did, I just didn't do it through the console I did it in the memory tab.
@cyberblast The thing is it works fine on the version before you merged the container classifications in, just after that it breaks.

**Comment by mikiones** [comment]
did you stop script while editing?

**Comment by cyberblast** [comment]
> development includes errors...

**Comment by torin555** [comment]
@mikiones The script wasn't running. The error breaks the script to the point of not running anything at all lol.
@cyberblast I'm not complaining :P just trying to troubleshoot

**Comment by cyberblast** [comment]
create an empty branch (tutorial?) in the screeps editor. 
switch to it in the world. the edit the memory

**Comment by torin555** [comment]
Well, figured out the problem, but it wasn't because an array wasn't being returned properly. It was because somehow an undefined room got added to my memory. As in the entire room was undefined. anyway got rid of that and it works now. But I'm not sure why an undefined room got added in the first place.

**Comment by cyberblast** [comment]
Great. 
As I mentioned above, I got quite some errors as well (costing my lifetime). Some things are strange...

**Comment by mikiones** [comment]
like array of flags are not always same size?
