### ISSUE TITLE
Invasion by others

### ISSUE THREAD

**Issue by Animatrixy** [ScreepsGamers/screeps.behaviour-action-pattern#158]
Not sure if this qualifies as a bug but here goes, i have walls built with ramparts in them, if another creep invades and breaks through the walls somewhere, my guards (melee and ranger) will not move to intercept them they just sit at the rampart waiting for the enemy to come to then, which 99% they don't, so i lose room with 3 - 4 guards doing nothing..

**Comment by cyberblast** [comment]
Yes it's the current behaviour. Working fine in some cases, bad in others. 
My be subject to change. So, I take it as Change Request..

**Comment by Animatrixy** [comment]
okies np ;-)

**Comment by cyberblast** [comment]
There is a switch now in parameters.js...
