### ISSUE TITLE
Improve spawn rules/limits

### ISSUE THREAD

**Issue by cyberblast** [ScreepsGamers/screeps.behaviour-action-pattern#159]
e.g. as lined out in #156 :
>In general the minEnergyAvailable helps to ensure that bigger creeps are created instead many smaller. 
 But it's not perfect. There are some problems with it. 

> I think the best solution will be to completely remove that function for relative comparison. Instead we should use minAbsEnergyAvailable as a function and calculate the min absolute Energy. That calculation could also take into account if all creeps have been killed, or such.

**Comment by mikiones** [comment]
i would prefer having tears insteed of blandly multiplying body like when level 5 add extra heal on end or fill beginning with 20 taught kind of deal

**Comment by cyberblast** [comment]
Yes I also thought about this approach. 
You mean something like 
```
{
  Level 1: [WORK], // just an example
  Level 2: [WORK,WORK,CARRY], // makes no sense 
  Level 3: [TOUGH,WORK,WORK,CARRY] // but shows principle
}
```
?

**Comment by mikiones** [comment]
yes

**Comment by cyberblast** [comment]
I tried to combine the best from both... 
Actually its the exactly same spawning rules as before. Each setup will maybe need some special attention and tuning of rules using the new capabilities...
