### ISSUE TITLE
Defcon storage bug

### ISSUE THREAD

**Issue by SirLovi** [ScreepsGamers/screeps.behaviour-action-pattern#163]
The code ATM is counting with rooms having storage.
Without storage it prints:

> creep.behaviour.worker:73
>             if (creep.room.storage.store.energy < storeNeeded) {
>______________________^
> TypeError: Cannot read property 'store' of undefined
>     at Object.module.exports.doWeHaveEnoughToWidral (creep.behaviour.worker:73:35)
>     at Object.module.exports.nextAction (creep.behaviour.worker:30:23)
>     at Object.module.exports.run (creep.behaviour.worker:7:18)
>     at Creep.run (creep:60:43)
>     at creep (creep:52:38)
>     at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)
>     at Function.<anonymous> (/opt/engine/node_modules/lodash/index.js:3346:13)

**Comment by BringerOD** [comment]
can you get the latest. I am not getting this error.

**Comment by SirLovi** [comment]
I had the latest. Do all your rooms have storage?

**Comment by cyberblast** [comment]
Added a hotfix.. 
b16e1842751f4b063c67476f895cd3b7cf6aba09

**Comment by SirLovi** [comment]
Fixed!
Needed:
`!creep.room.storage ||`

**Comment by BringerOD** [comment]
Good catch,  I have storage.
