### ISSUE TITLE
flagEntries does not have a foreach

### ISSUE THREAD

**Issue by BringerOD** [ScreepsGamers/screeps.behaviour-action-pattern#164]
room line 326 and 353
claimerMaxWeight, privateerMaxWeight function

'                            flagEntries.forEach(calcWeight);'

I put a try catch around it for now.

It stems from the 'FlagDir.filter([FLAG_COLOR.claim, FLAG_COLOR.claim.reserve]);' function returning a 0,  which would not have a forEach function.

**Comment by cyberblast** [comment]
hmm, thats strange. 

![image](https://cloud.githubusercontent.com/assets/20269868/18563903/a01fbb7e-7b89-11e6-8192-0275c49cb2e2.png)

When nothing its found I get an empty array, as expected, which should have forEach. 

Is this behaviour reproducable at your side?

**Comment by cyberblast** [comment]
ok, found it. should be fixed now... 
Ocurred only when there are no flags...

**Comment by BringerOD** [comment]
Confirmed fixed.  Thanks!
