### ISSUE TITLE
Offtopic or general

### ISSUE THREAD

**Issue by cyberblast** [ScreepsGamers/screeps.behaviour-action-pattern#172]
Hey! 

Its so much fun and exciting to see things evolving! 

To be honest: I didn't use git before, as I am using other tools during work times (mostly TFS). 
In the meanwhile I really love git and the open community. 

The only thing I am missing is a communication channel besides issues. A microblog would be great. Simply for direct communication - above any issue. 

So this is an approach. I don't know if this is sufficient and will work, but I'll give it a try.

**Comment by cyberblast** [comment]
This project started with a handful of modules and without any attention.  
Now we have a quite large repository. Everything is well thought, tested and validated. Of course there are  errors, issues, etc, all the time. That is part of it. But we are solving them and advance from topic to topic. 

What I maybe have underestimated is the effort to manage this growing project. 

All of you have great ideas and are doing a great job implementing complex things. 
But I have a big plea: 

Of course there is no sense to develop build automation when you have your first room. There are other things which need to be taken care of. e.g. harvesting. 

But what about those topics which ARE possible? 
When I have a look into the list of open issues I get dizzy. 
Its really very hard if everybody just picks what he/she is interested in, regardless of the current state of the repository. 

There is a vague plan, an order of topics. 
The most important component are iterations (milestones). 

Did you know all issues (or most of them) are assigned to a milestone, which itself has a certain time goal?

Please have an eye on it. 
Of course you may still prefer topics on your own opinion. 
It's only a plea to consider the global sequence. 

We need to coordinate what we do.

**Comment by FaosLabs** [comment]
Solid work Cyberblast. While I don't use your code right now, I've starred it and will be watching development. I think something good is going to come out of it, or rather, something better than what it already is.

**Comment by cyberblast** [comment]
Thanks, you're welcome!

**Comment by cyberblast** [comment]
I tries to set up a more flexible structure of topics, not just milestones. Please find different topic "streams" under "projects", and feel free to pick (self assign) cards you would like to work on. 
If your account is not listed to self assign an issue, please ask for it (git@cyberblast.org).
