### ISSUE TITLE
Trouble with simulation room sources

### ISSUE THREAD

**Issue by Ondalf** [ScreepsGamers/screeps.behaviour-action-pattern#195]
Cannot find sources automatically. Have to add manually.

Suggestion: when room name == 'sim', search sources and update array for example once when MEMORY_RESYNC_INTERVAL == true. 

Adding third source caused grey hair, since I had to force it ~3-4 times into memory.

**Comment by cyberblast** [comment]
Hi Ondalf, 

you can also complete remove the sources node from memory. It will the be created again (with the new sources).  

The room switch feels wrong, but makes sense eventually.

**Comment by Ondalf** [comment]
Didn't think about that! Thanks. Works quite well in simulation room. Spawn wasn't added into memory either at the beginning and road spawning complained about it.

**Comment by cyberblast** [comment]
yup. spawns only get loaded every 'MEMORY_RESYNC_INTERVAL' loops (100 by default)... 
could be reduced to 1 in sim room...
