### ISSUE TITLE
Issues with latest code

### ISSUE THREAD

**Issue by Animatrixy** [ScreepsGamers/screeps.behaviour-action-pattern#201]
Using the latest dev build i get the following on the console

TypeError: Cannot read property 'multiBody' of undefined
    at Setup.maxCost (creep.Setup:142:46)
    at Room.get (room:424:79)
    at Room.get (room:433:61)
    at Object.nextAction (creep.behaviour.hauler:40:30)
    at Object.run (creep.behaviour.hauler:7:18)
    at Creep.run (creep:81:43)
    at run (creep:53:38)
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)

any ideas ?

**Comment by SirLovi** [comment]
Did the issue resolve itself by time? Maybe by the problematic creep dying?
This looks like the Setup module had some problems..

Did you try deleting all your .js files and then pasting fresh dev build?

**Comment by ValkyrX** [comment]
Hi I have restarted my room so will update seemed to have something to do with haulers, I used a clean dev build so will update soon, its only on lvl 2 yet got wiped again lol ;-) need to do something about defense me thinks

**Comment by SirLovi** [comment]
Yup.. I've also noticed that our build can be a bit slow in the early game..
I tried to fix this issue by increasing the number of upgraders or workers to fine tune the individual situation and have tower (RCL3) as soon as possible

**Comment by Animatrixy** [comment]
Ok so after a respawn i haverun the new code, it was ok ish until rcl 4 where i get the same error as above, its clean code with no alterations, also i noticed that no defenders will spawn at all even from rcl 2

**Comment by cyberblast** [comment]
Hi, sorry for the late answer. 
May hopefully be fixed with the latest commit 91c0826.

**Comment by Animatrixy** [comment]
Hi there thanks for reply, i will update to the new build and advise when it gets to rcl 4 thats when the issue seemed to be an issue.

**Comment by Animatrixy** [comment]
Just to say controller now at rcl 4 and all is well, its a 4 that everything went wrong so i think we can list this one as fixed ;-)

**Comment by cyberblast** [comment]
Great :) thank you for reporting
