### ISSUE TITLE
Auto Sell Minerals when > MAX_STORAGE_MINERAL

### ISSUE THREAD

**Issue by cyberblast** [ScreepsGamers/screeps.behaviour-action-pattern#204]
* auto sell only for mineral harvested in current room. 
* define MINERAL_AUTOSELL_AMOUNT. 
* when Mineral >= MAX_STORAGE_MINERAL + MINERAL_AUTOSELL_AMOUNT, sell until Mineral <= MAX_STORAGE_MINERAL

**Comment by Dasku** [comment]
Will this sell via the market for credits?

**Comment by cyberblast** [comment]
Thats the idea.

**Comment by Dasku** [comment]
Made my first sale today, worked great! 44k Credits. 

Room "E55N3" executed an order!
Result: OK
Details:
{"created":"14098532","type":"buy","amount":76157,"remainingAmount":76157,"resourceType":"H","price":1.01,"roomName":"E44N43","id":"57eea4b6ddc9ea5f110e627b"}

**Comment by Dasku** [comment]
How does it pick the price by the way? Does it just fill the order offering the most credits?

**Comment by SirLovi** [comment]
Looking at the code:
It checks if you have MIN_MINERAL_SELL_AMOUNT
Then it gets all orders of that mineral type (with distance cost added) and sorts them by price
If it finds some, it accepts the deal of the first one on the list.
(I hope the first on the list is the one with the highest price, not the lowest :pray: )

**Comment by cyberblast** [comment]
Correct, but: 
It sorts them by price (ascending) and takes the **last** one. ([Array.pop](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/pop))

But still requires improvement to take the best price / distance ratio... 
Or at least lowest distance of those having the same "highest" price (e.g. "1" comes quite often...)
