### ISSUE TITLE
Team / Friend / Non-aggressive pack. 

### ISSUE THREAD

**Issue by Dasku** [ScreepsGamers/screeps.behaviour-action-pattern#207]
Hey, great work here firstly.

Would it be possible to add a value to parameter's for friend/team or simply non-aggression. I've not played long but I have spoken to some people who want to stay neutral or even team up. 

Could this be added via parameter's or a flag in their room to indicate they are not a threat (unless they attack you first)?

I did a quick search and couldn't find any other issues like this.
Thanks

**Comment by Dasku** [comment]
global.PLAYERWHITELIST = ['Asku', 'Source Keeper'];
var closestHostile = tower.pos.findClosestByRange(FIND_HOSTILE_CREEPS, { filter : c => .indexOf(PLAYER_WHITELIST, c.owner.username) == -1 });

**Comment by cyberblast** [comment]
Hi Dasku, 

There is issue #42, which could be a solution for your request. But there's a lot to do until this is reached. 

A simple array of player names not to treat as enemies (e.g. when entering your rooms) could be implemented quite fast. 

Feel free to propose an implementation of a whitelist as commit 😉

**Comment by Dasku** [comment]
Sure thanks

**Comment by Dasku** [comment]
Ok so I think I've got the code, how do I send you a commit or a pull request?
