### ISSUE TITLE
Store stops controller upgrading (prior to upgraders)

### ISSUE THREAD

**Issue by Dasku** [ScreepsGamers/screeps.behaviour-action-pattern#211]
I've now built a store, however everything is focused on filling said store and all upgrading has stopped. 

I have changed my parameters so it should upgrade after store has 30k energy (20k minimum) as my controller is still only level 4.
"
   MAX_STORAGE_ENERGY: 30000,// stop storing energy when reached
    MIN_STORAGE_ENERGY: 20000,// prefer storing energy until reached
"

However my store has 40k energy and instead of going back to upgrading focus is still filling the store. 

I even have an idle worker next to the store (in pic below, as an aside, its idling next to the spawn/store not the controller?), is there anyway to make worker upgrade instead of idling? (taking energy from store or either container near by, or picking/mining first as the worker is not even carrying energy)

![](https://i.gyazo.com/4f5cda6782277ed789ade74e388f4cf5.png)

This may just be a minor issue as I'm low level which works itself out once I get links and upgraders at level 5, however until then I'd still want at least some upgrading to be done as to not waste loads of time filling the store when I should be focusing on leveling quicker.

Thanks

**Comment by Dasku** [comment]
Also, not sure if this is important but when privateers return from harvesting adjacent rooms, they choose to store the energy they bring back instead of using it to upgrade.

**Comment by Dasku** [comment]
Also currently, my Controller would downgrade before the store reaches max capacity if i can't find a way to stop storage.

**Comment by cyberblast** [comment]
Hi Dan, 

you need at least one container in front of the controller (within range of 3 fields)! 

As soon as you have it (+ some time until cache is updated), the upgrader will spawn. 

There is no need for containers "somewhere" (as shown in your screenshot), if you build some (after the required one at the controller) try to put it within the range of a source (max 2 fields range). 

Storage level has only impact on the SIZE of the upgrader creep. If you have a good economy, few streets, some remote harvesters (privateers), your storage level will increase, allowing larger (or additional) upgrader creeps. However, a minimal upgrader creep will always be spawned (having the required container or link, (you should keep both)). 

There may still be a bug - I am unsure why the worker isn't upgrading... 

I hope this helps

**Comment by Dasku** [comment]
Ok thanks for your response, I'll sort the containers now. Not sure about the worker either, was starting to panic a bit due to the downgrade.

**Comment by cyberblast** [comment]
I added the worker problem as new bug #212.

**Comment by cyberblast** [comment]
you can also put a pioneer flag in your room to temporarily increase the number of workers ;) 
(if you want to speed up building)

**Comment by cyberblast** [comment]
looks good ;) 
I also found the worker problem. They should help upgrading now (when MAX_STORAGE_ENERGY reached). 
Going to close the issue...
