### ISSUE TITLE
Claiming bug

### ISSUE THREAD

**Issue by Animatrixy** [ScreepsGamers/screeps.behaviour-action-pattern#216]
latest build if setting flag to reserve or claim no claimer is spawned

**Comment by cyberblast** [comment]
I can't confirm that. 
Claimer will only spawn when at least 1300 energy available and min 60% of all spawns/extensions filled. 
Claimer also have lowest priority, which means any other type will be preferred to spawn if its required. 

Did you wait a while? 
Still no claimer?
