### ISSUE TITLE
Alliance

### ISSUE THREAD

**Issue by SirLovi** [ScreepsGamers/screeps.behaviour-action-pattern#218]
http://www.leagueofautomatednations.com/map

There's an option of creating our own alliance with our own Slack etc.

Should we go public like this? Would you like to?

**Comment by cyberblast** [comment]
Sounds interesting 😁 

How would we like to call it? 

Some Ideas: 
* Screeps Gamers
* Open Collaboration
* The Society

**Comment by SirLovi** [comment]
How about: 

- The Unity

**Comment by cyberblast** [comment]
Hmm. yes, but I'd like to include the kind of what we are. a loosely gathered group of people who like to work together on the same code and support each other doing so... 

* Open Collaboration Society [OCS]

**Comment by SirLovi** [comment]
+1 to OCS

**Comment by cyberblast** [comment]
Ok, so it's created :) 

Anybody wants to join? 
Of course it not required to join the alliance to use our code or contribute to this repository.

**Comment by Dasku** [comment]
Sign me up! :)

**Comment by cyberblast** [comment]
Added! Welcome to OCS :)

**Comment by Dasku** [comment]
When next month starts, are we all going to start fairly close to each other? Like all start near a specific corner?

**Comment by cyberblast** [comment]
Sure, it would be great to move closer together. But there is no "reset" at the end of the month. 

When you have a look at the [alliance map](http://www.leagueofautomatednations.com/map), you can see there is a huge free space in the north western sector. That would be a good place for expansion. I and SirLovi are already in that area. 

There are also some novice areas in W2xN21x & W5xN1x. You could move there at every time...

**Comment by Dasku** [comment]
So at the end of the month I keep my current rooms next month? Nothing resets? If so Ill move now so I can make 3 rooms before reset

**Comment by cyberblast** [comment]
Yup, the only thing which will reset are the leaderboards. 
Your rooms will stay the same!

**Comment by Dasku** [comment]
Cool, on my way

**Comment by cyberblast** [comment]
Have a good trip! 🚌

**Comment by Dasku** [comment]
Got a problem, when I moved and picked a new room it wont spawn a worker. I get the following error, code unchanged. 
TypeError: Cannot read property 'typeWeight' of undefined
    at Setup.existingWeight (creep.Setup:115:40)
    at Setup.multi (creep.Setup:138:35)
    at Setup.parts (creep.Setup:147:26)
    at Setup.buildParams (creep.Setup:54:29)
    at StructureSpawn.Spawn.createCreepBySetup (spawn:27:32)
    at probe (spawn:21:57)
    at baseFindIndex (/opt/engine/node_modules/lodash/index.js:326:11)
    at Function.<anonymous> (/opt/engine/node_modules/lodash/index.js:3241:23)
    at StructureSpawn.Spawn.loop (spawn:23:15)
 


**Comment by cyberblast** [comment]
Have a try 6d6757e

**Comment by Dasku** [comment]
Fixed it, thanks a lot!!
