### ISSUE TITLE
Hauler error

### ISSUE THREAD

**Issue by SirLovi** [ScreepsGamers/screeps.behaviour-action-pattern#219]
I suspect the problem is with too many parts... Maximum per creep is 50

![capture](https://cloud.githubusercontent.com/assets/20193391/19411316/bdc1a948-92ff-11e6-84f6-c9be296900dd.PNG)

`W55N32 > Offspring failed: ERR_INVALID_ARGS, spawn params: {"setup":"hauler","name":"hauler-2850-1","parts":["carry","carry","move","carry","carry","move","carry","carry","move","carry","carry","move","carry","carry","move","carry","carry","move","carry","carry","move","carry","carry","move","carry","carry","move","carry","carry","move","carry","carry","move","carry","carry","move","carry","carry","move","carry","carry","move","carry","carry","move","carry","carry","move","carry","carry","move","carry","carry","move","carry","carry","move"],"cost":2850,"mother":"Spawn3","home":"W55N32","breeding":1}`

**Comment by cyberblast** [comment]
Possibly fixed with cc1e817. 
But the same problem may still exist with other types. Still working on it...

**Comment by cyberblast** [comment]
Also in upgrader setup
