### ISSUE TITLE
New build issues, 

### ISSUE THREAD

**Issue by ValkyrX** [ScreepsGamers/screeps.behaviour-action-pattern#229]
The files in the download do not include the reallocating script ? so on loading new code get an error cant find script

**Comment by Dasku** [comment]
I think the current dev branch is mid progress with the mineral selling code, use the master branch code until its updated again.

**Comment by cyberblast** [comment]
Sorry, has been a long night when that 'incomplete' commit b6d0735890b4a6224b411d266555070bc6b4d812 happened. 
Should be solved since 2d1eaf4d8c03e4d63d2971ece43b78b83c8b0b0d.
