### ISSUE TITLE
ERR_TIRED error message ?

### ISSUE THREAD

**Issue by Dasku** [ScreepsGamers/screeps.behaviour-action-pattern#231]
ERR_TIRED
room: E55N3
creep: miner-650-3
action: harvesting
target: 579fab8db1f02a3b0cff07f7

Repeats a few times and then goes back to normal (its always on the miner on minerals, never at sources).

Not sure if this is a problem or just a timing issue.

**Comment by cyberblast** [comment]
Thats strange. 
ERR_TIRED is the expected error code when the extractor is "busy". 
But the error shouldn't be shown, as it is expected to be like that. 
Did you change anything?

**Comment by Dasku** [comment]
I'm constantly fiddling with bits trying to learn what everything does/how it works, so could be an error on my part. Ill let you know if it comes up again.  I'm pretty sure it happened with code id downloaded though (maybe changed some parameters only). It seems to come and go, didnt see it much last night but I had the Terminal full error spamming all night so easy to miss it.

**Comment by cyberblast** [comment]
There will also come a lot of those (maybe with other ERR_*), when there is an invader harming your creeps and they are losing necessary parts but still trying to behave as "normal". 
So, I'll close this one for now. 
If it happens again (under common condition) please reopen!

**Comment by mikiones** [comment]
this error is when you try mine mineral and it is on cool down time

**Comment by cyberblast** [comment]
Yes, thats what i meant with "busy" extractor.
