### ISSUE TITLE
Terminal Energy MAX required?

### ISSUE THREAD

**Issue by Dasku** [ScreepsGamers/screeps.behaviour-action-pattern#233]
Hey,

After my first sale with my terminal with the following settings: 
MAX_STORAGE_MINERAL:20000, // keep a max of each type of minerals in store
MIN_MINERAL_SELL_AMOUNT:20000, 
MAX_SELL_RANGE: 40, 
TERMINAL_ENERGY: 100000, 

Now my terminal has 290k Energy and 10k minerals so it will not make another sale. Do we need a MAX Energy in a terminal setting to ensure they dont fill up with energy and leave no space for minerals?

**Comment by Dasku** [comment]
I've been getting the following error every few minutes, I think due to the terminal being full.
ERR_FULL
room: E55N3
creep: hauler-1500-1
action: null
target: null

**Comment by cyberblast** [comment]
TERMINAL_ENERGY is meant to be MIN as well as MAX, it should simply have that much energy (+- 5%). 
But I also have one room where it went wrong somehow (180k). Strange, all the others are fine. 

There should also be a validation if it's (completely) full. regardless of its energy level.

**Comment by Dasku** [comment]
Yeah seems odd, in my 2nd room the terminal has stopped around 96k energy, however the minerals are still going to the store instead of the terminal (I assume because my store minerals isnt at max amount yet). Will check on this later tonight when I get home from work. Maybe the validation should be if the terminal is full and energy is > than TERMINAL_ENERGY it removes some energy to make room for minerals?

**Comment by cyberblast** [comment]
I agree. We can use the new reallocation action for that energy move. 

And yes, the storage will get filled first, as that mineral should be used for your labs. The auto sell mechanic is more like an emergency plan when stocks are running full. 
(And still we have no labs running 😉)
