### ISSUE TITLE
Claimer Behavior

### ISSUE THREAD

**Issue by dkluempers** [ScreepsGamers/screeps.behaviour-action-pattern#240]
A room was claimed and the claimer issued the following message.

ERR_INVALID_TARGET
room: W63N54
creep: claimer-1300-1
action: claiming
target: 57ef9cc086f108ae6e60cc70

Per cyberblast it is not a major issue since everything actually worked.  The claimer claimed the room, I think it then tried to reserve it and got the error since it was already claimed.  He suggested an update at some point to have it wait for a new job.  I think the code may need to check for the error when it tries the reserve it and just proceed to idle if it see that error.  I will take a crack at that code change for my next room claim.

**Comment by cyberblast** [comment]
Thank you for reporting and opening the issue.

I had a look at the code. 
I guess the claimer keeps the target (controller) and the action, as there is no 'unregistration'. It then keeps trying to claim and/or reserve it. 
Other actions have an isValidAction or isValidTarget rule, which will be evaluated each tick to step out (or step out explicitly be clearing creep.data.actionName and creep.data.targetId). 
Those are missing here. 

'action.work' may also get reduced to simply implement claiming (not reserve or attack controller), allowing clear validility rules. 

The claimer behaviour is already implementing 'idle', which should work once stepped out of the claiming action.

**Comment by dkluempers** [comment]
I will validate as soon as I can get enough control points to claim another room.

**Comment by dkluempers** [comment]
It is working correctly.  I claimed a room this morning and it worked perfectly - no error messages.

**Comment by cyberblast** [comment]
great! :) thx
