### ISSUE TITLE
Population Issue (spawns have stopped) 

### ISSUE THREAD

**Issue by Dasku** [ScreepsGamers/screeps.behaviour-action-pattern#243]
Hey,

Just got the newest code, but my population has dropped right down to 2 miners, 1 hauler and 1 worker. No privateers, all extensions and spawn is full, any ideas?

**Comment by Dasku** [comment]
I think I sorted it, I lowered my min and max energy storage to 5k (as thats all my store has) and its spawned a privateer again.

**Comment by cyberblast** [comment]
Yup. it's due to the MIN Value. It then tries to save as much energy until reached. 
50k is indeed a bit high for the early game...

**Comment by Dasku** [comment]
Ok cheers, good to know.
