### ISSUE TITLE
Energy Efficiency with Links & Privateers 

### ISSUE THREAD

**Issue by Dasku** [ScreepsGamers/screeps.behaviour-action-pattern#255]
![image](https://cloud.githubusercontent.com/assets/22677773/19895326/42135b7e-a048-11e6-9799-6b5ad8c11a24.png)

The picture is my current and planned setup. Each red circle is where I imagine a link to be.

The idea is that the centre link is continuously being filled from the north, west and south links. (Privateers should use the link instead of the store to save lots of travel time). 

Now the link on the West is not being used by the privateers mining the room to the west. (maybe because links are not a drop off target, maybe because the west and centre link are never empty)

In order for this to work I think the following requirements must be met:
1) Privateers prioritise Links over Storage (If closer, which should be true if joining the room from a side)
2) Ensure centre link is emptied fast to allow other links to send energy to the centre. 
3) Workers and Haulers empty the centre link as priority (before picking), then follow normal priorities.
4) 1 hauler and 1 worker should be able to keep the centre link empty while charging, fuelling and building/repairing.
5) Workers and Haulers should charge your controller container. 
6) ? Upgraders take energy from link and put in container if link has energy and container/upgrader has space
7) ? Allow links to move minerals for centre SK room mining 

I think this would start to give huge energy benefits per privateer making them much more efficient. This benefit would be compounded as you grow and have more rooms (especially when mining centre rooms, either with privateers (maybe special kind) or with miners & haulers, as it cuts half the travel time).

Any thoughts?

**Comment by cyberblast** [comment]
Its already implemented, but not exactly as your transcription. 
Privateers will already go to the nearest 'link or storage', but not every link is valid. 
When you use links for your miners (without containers) it will be full quite fast. Privateer dropoff will charge it too much. There is also a cooldown for the links. That doesnt work well. 
So "miner links" are currently not allowed for privateers. 

The "center link" will also already be always emptied as fast as possible. But it needs to be next to the storage. 

The upgrader link will always be filled (from the other links), for the upgrader. 

So you will need 4 links for the base infrastructure (2 miners, 1 storage, 1 upgrader). 

You can get up to 6 links, so you can 2 more for the privateers. 

Links cant be used for minerals.

**Comment by Dasku** [comment]
Ahh ok, great to know, thanks a lot.
