### ISSUE TITLE
invading /facepalm

### ISSUE THREAD

**Issue by Gestic** [ScreepsGamers/screeps.behaviour-action-pattern#256]
so a pal and i gathered troops to invade, he went in one entrance to the enemy base and i went in another since we found out that even though he is in the whitelist if my creeps get near his, my creeps damage his. anyways, i place yellow flag in base, then red flag then place orange on tower. creeps start streaming in but instead of attacking anything in the base or any enemy creeps all my creeps start heading towards his.. i figure this is because red flag so i delete that. the creeps do a pause and i figure that all's good. nope, they keep heading towards his creeps and start attacking them. i had more creeps and they were bigger so all his creeps were destroyed by the towers or my guys. anyways i figure ok there's a few left so they would attack the orange flag since there is no red one. nope they chase around his creeps instead. lol /facepalm. defender lost one creep total. oh i had about 50 2000+ melee creeps and he had around 50 1300+ range and 25 1300+ melees. the base had no walls, rc6 with 2 towers and no defenders.

**Comment by Dasku** [comment]
Ok I see the problem here, the whitelist filter is not applied to all the attacks in creep.action.invading.js

ill try and fix this and submit to cyber to look at

**Comment by Gestic** [comment]
yeah i thought that it would be the invading module strange though is that we have done this before and never had that behaviour. *shrug*

**Comment by cyberblast** [comment]
Ouch. 
Yes its not yet implemented in the offensive scripts. 
Sorry.

**Comment by Gestic** [comment]
hehe no problem i just found that this was the most comical moment ive had in the game so far. haha

**Comment by cyberblast** [comment]
But I will rate this as bug nevertheless 😉

**Comment by cyberblast** [comment]
addressed with 2b25dee60fda6cf5b0e735829eae0faf329e3d0c

**Comment by Gestic** [comment]
thanks for the quick response and work /salute
