### ISSUE TITLE
Worker goes idle without reason

### ISSUE THREAD

**Issue by cyberblast** [ScreepsGamers/screeps.behaviour-action-pattern#258]
there is work to do and there is energy ... but it doesnt work :( 
It did construct one part of that construction site, then stoppped when energy was empty.

![image](https://cloud.githubusercontent.com/assets/20269868/19941388/38161f74-a130-11e6-843b-10ab1c67558d.png)

it went back to work after a few loops. 😕

**Comment by cyberblast** [comment]
may be the withdrawing.maxPerAction = 2 limit (which makes no sense at all).

**Comment by SirLovi** [comment]
This kinda happens too in early RCL where there's only few spaces for workers to mine...
Rest just idles.. instead of moving to the source which would speed up the work..
![capture](https://cloud.githubusercontent.com/assets/20193391/19943134/6e8496b6-a136-11e6-8513-f6ed5aa4a93f.PNG)

**Comment by cyberblast** [comment]
Hmm yes. But that's an other reason. 
It's more or less 'by design'.  

Hmm. we could increase allowed harvester crowd for lower room levels..
its currently `target.targetOf.length < target.accessibleFields`. 

Or simply add a  +1. lowest cpu usage and could solve the problem already...
