### ISSUE TITLE
Add "dismantling" Action

### ISSUE THREAD

**Issue by cyberblast** [ScreepsGamers/screeps.behaviour-action-pattern#26]
creep.dismantle  
by flag or for "workers" invading  
also for privateers to remove walls blocking way or to get energy from any unknown tructure

**Comment by cyberblast** [comment]
Could be for privateers going into invasion to dismantle walls etc

**Comment by mikiones** [comment]
any idea how choose target to dismantle ? in my working code i have that privateers have 
   Creep.action.robbing,
   Creep.action.picking,
   Creep.action.dismentle,
   Creep.action.harvesting,
