### ISSUE TITLE
Useless Worker

### ISSUE THREAD

**Issue by torin555** [ScreepsGamers/screeps.behaviour-action-pattern#263]
My worker has started acting more like a hauler. It never upgrades the controller anymore because it spends all it's time either taking energy from the miner containers to the storage or sitting at the storage removing energy and putting it straight back in. (The haulers do that as well but it's not as bad for them to do it because it means that they have nothing else to do.)

**Comment by cyberblast** [comment]
at which RCL? Do you have a storage? 
The worker will not help upgrading once there is a storage. 
We've had a discussion about if and when the worker should stop upgrading, and there are different opinions. This was when the worker was not allowed to upgrade as soon as there is an upgrader - that should be possible now. 

But the idea is to have dedicated miners and dedicated upgraders. So at some point workers should give that role away completely. 
The reason why this is also important is, that there is some logic to increase/decrease the upgrader size depending on storage energy level. The storage level controls upgrader size (and numbers) and the upgrader controls storage level. That works quite well. And I see the worker as a disturbing factor in this symbiosis. 

The worker got a new role instead. When idle (and there is enough energy) it will fortify walls. Which is cheaper than towers doing it. (=> new threshold MAX_FORTIFY_LIMIT)

When the worker goes into idle mode the reason should be there is not enough energy. So in this case it would also be a bad idea to send him take energy from the storage for upgrading...

**Comment by torin555** [comment]
RCL 4 and yes I have a storage, the problem is that the upgrader is *way* too slow on its own.

**Comment by cyberblast** [comment]
because of its size. but its size is that small because of your storage level ;)

**Comment by cyberblast** [comment]
forkmantis is currently working on tiered storage thresholds - this will make it way smoother at RCL 4 ...

**Comment by cyberblast** [comment]
multiple upgrader will spawn as well. 
maxCount is: Math.max(1, Math.floor((room.storage.store.energy-MAX_STORAGE_ENERGY) / 100000))

for each full 100k above MAX you get one additional upgrader

**Comment by Dasku** [comment]
Spawn 2 upgraders. (I do this most of the time anyway)

in creep.setup.upgrader.js change the maxCount return like so:

setup.maxCount = function(room){
    if (room.situation.invasion || 
        room.conserveForDefense || 
        (room.containerController.length + room.linksController.length) == 0 ) 
        return 0;
    if( room.controller.level == 8 ) return 1;
    return 2; // room.storage ? Math.max(1, Math.floor((room.storage.store.energy-MAX_STORAGE_ENERGY) / 100000)) : 1;
};

This will drain your storage to keep both upgraders going as fast as possible. Should be fine until you get terminals and minerals etc at level 6.

**Comment by cyberblast** [comment]
yes, but in the end its the same. except that you will always have an empty storage and no buffer. 
you can only burn what comes in, no matter how you do it

**Comment by Dasku** [comment]
That is true, I have no buffer at all this way.

**Comment by cyberblast** [comment]
I do :P

**Comment by cyberblast** [comment]
a low storage will also prevent fortifying

**Comment by torin555** [comment]
At the moment I have 138k energy in storage, I've made my min storage energy 5k and my max storage energy 30k, but it isn't spawning a second upgrader, did I misunderstand what you meant cyber?

**Comment by cyberblast** [comment]
yup, should spawn a second one then. 
hive filled?

**Comment by torin555** [comment]
Everything's full, haulers sitting at storage taking out and putting back in like always, E32N43

**Comment by torin555** [comment]
"Always" being when they have nothing else to do

**Comment by cyberblast** [comment]
try Creep.setup.upgrader.maxCount(Game.rooms('E32N43'))

**Comment by torin555** [comment]
In console?

**Comment by cyberblast** [comment]
yup

**Comment by torin555** [comment]
[11:39:09 AM]TypeError: Game.rooms is not a function

**Comment by cyberblast** [comment]
my fault ^^ 
`Creep.setup.upgrader.maxCount(Game.rooms['E32N43'])`

**Comment by torin555** [comment]
1

**Comment by cyberblast** [comment]
`MAX_STORAGE_ENERGY` ?

**Comment by torin555** [comment]
30000

**Comment by cyberblast** [comment]
ensured via console?

**Comment by torin555** [comment]
yeah

**Comment by cyberblast** [comment]
kk ^^ 
hmm I don't get it

**Comment by cyberblast** [comment]
I got already multiple upgrader some times...

**Comment by Gestic** [comment]
ah damn why didn't i see this? though it was just emails. this msg is a placeholder that i can come back to so bump?  :p ah love being a nub

**Comment by torin555** [comment]
Ah I think I see the issue

**Comment by torin555** [comment]
`return room.storage ? Math.max(1, Math.floor((room.storage.store.energy-MAX_STORAGE_ENERGY) / 100000)) : 1;`
It's a ratio over 100,000. 107,000/100,000 is 1.07/1, so unless it rounded up it's going to spawn 1 until I get to 230,000 energy

**Comment by cyberblast** [comment]
ah, yes you are right ^^.

**Comment by torin555** [comment]
Well for the moment I'll just manually spawn more upgraders.

**Comment by cyberblast** [comment]
or make it a Math.ceil ;)

**Comment by torin555** [comment]
Yeah rounding up works too, I'll try that out.

**Comment by torin555** [comment]
It only wants 1 argument, would I just remove the "1, " before the ratio?

**Comment by torin555** [comment]
No that probably wouldn't work...

**Comment by torin555** [comment]
Hmm, the maxcount is still 1, even though it should be rounding up

**Comment by cyberblast** [comment]
> It only wants 1 argument, would I just remove the "1, " before the ratio? 

what exactly do you mean?

**Comment by torin555** [comment]
I made it:
`return room.storage ? Math.ceil(Math.floor((room.storage.store.energy-MAX_STORAGE_ENERGY) / 100000)) : 1;`
because the 1 in front is for math.max, it does mean that if you have no storage it won't spawn any, which is an issue. But it wouldn't be making it still return 1...

**Comment by torin555** [comment]
oh shit

**Comment by torin555** [comment]
nevermind

**Comment by torin555** [comment]
I'm an idiot

**Comment by cyberblast** [comment]
no. errors are a part of development. ;)

**Comment by torin555** [comment]
There we go, `return room.storage ? Math.max(1, Math.ceil((room.storage.store.energy-MAX_STORAGE_ENERGY) / 100000)) : 1;` works like a charm. Thanks :)

**Comment by cyberblast** [comment]
![image](https://cloud.githubusercontent.com/assets/20269868/20029048/13d08d3e-a342-11e6-88d1-7e6075a7d0be.png)
using the original code (with Math.floor).
