### ISSUE TITLE
Close sources causes miner position issues. 

### ISSUE THREAD

**Issue by Dasku** [ScreepsGamers/screeps.behaviour-action-pattern#264]
![image](https://cloud.githubusercontent.com/assets/22677773/20004695/b56f1268-a285-11e6-9086-e1a5d8e6bbc6.png)

In the picture I have 2 sources next to each other. Both miners are trying to stand on the same square to mine, so one just stands there idle, instead of trying to find another suitable location (1 square away).

I have tried delete Game.creeps['name'].data.determinatedSpot on both creeps, sometimes fixes this issue, sometimes not. Generally they go back to 1 being idle after a while.

I think this issue is because the sources are next to each other which initially I thought would be great for efficiency. I'm worried this will get even worse when I want to add a link to the following square:

(F)(R)(L)(C)
(R)(R)(R)(R)
(W)(W)(S)(S)

F = Floor
R = Road
(L) = Link
(C) = Container
(W) = Wall
(S) = Source

I was hoping both miners would fit in the 1 square gap (R) between sources and container/link so they can share a container and link. However not sure if this will work.

Any thoughts?

**Comment by cyberblast** [comment]
I will close this one as sirLovi mentioned it is working now (in slack), he also has adjacent sources... 
Please reopen this issue if it occurs again
