### ISSUE TITLE
Worker Withdrawing Priority

### ISSUE THREAD

**Issue by torin555** [ScreepsGamers/screeps.behaviour-action-pattern#271]
If you have haulers, wouldn't it be better to withdraw from the storage rather than going all the way to the mines to get energy, and let the haulers bring the energy from the mining containers to the storage for workers?

**Comment by erik-smit** [comment]
I removed picking and uncharging from the list and added this in my creep.behaviour.worker.js
```
            if( creep.room.population && creep.room.population.typeCount['hauler'] && creep.room.population.typeCount['hauler'] == 0 ) {
                priority.unshift(Creep.action.picking, Creep.action.uncharging);
            }
```
