### ISSUE TITLE
Merge Privateers with Workers & Pioneers

### ISSUE THREAD

**Issue by cyberblast** [ScreepsGamers/screeps.behaviour-action-pattern#55]
Just build workers. Once the room is saturated try to discover other sources.

**Comment by mikiones** [comment]
i kind of run now that setup,changes i did:
when i'm worker and i idle change me into privateer
when i'm privateer and i have come back from mining change me to worker.
works nicely so far.

**Comment by SirLovi** [comment]
Sounds nice. But it may become messy, looking at my hordes of privateers..

**Comment by mikiones** [comment]
well i'm starting colony from 0 so it is best way to utilise idle workers.
