### ISSUE TITLE
Add "robbing" Action

### ISSUE THREAD

**Issue by cyberblast** [ScreepsGamers/screeps.behaviour-action-pattern#77]
e.g. for privateers
to withdraw energy from foreign extensions, containers, links, storage, labs.

**Comment by cyberblast** [comment]
Can anybody confirm it's working as intended? (can't validate actually)

**Comment by mikiones** [comment]
it works just not for containers.

**Comment by cyberblast** [comment]
Ok, I'll close this one. There is an extra issue for the container bug: #141
